version: '3'
services:
  cozastore-product-service:
    build:
      context: ./
      dockerfile: product-service
    ports:
      - "8080:8080"
    container_name: cozastore-product-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://cozastore_mongo_db:27017/
      REDIS_HOST: cozastore_redis
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    depends_on:
      - cozastore_mongo_db
    networks:
      - cozastore-network

  cozastore-order-service:
    build:
      context: ./
      dockerfile: order-service
    ports:
      - "8081:8081"
    container_name: cozastore-order-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cozastore_mysql_db:3306/cozastoreVault
      REDIS_HOST: cozastore_redis
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    depends_on:
      - cozastore_mysql_db
    networks:
      - cozastore-network

  cozastore-blog-service:
    build:
      context: ./
      dockerfile: blog-service
    ports:
      - "8084:8084"
    container_name: cozastore-blog-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://cozastore_mongo_db:27017/
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    depends_on:
      - cozastore_mongo_db
    networks:
      - cozastore-network

  cozastore-carousel-service:
    build:
      context: ./
      dockerfile: carousel-service
    ports:
      - "8082:8082"
    container_name: cozastore-carousel-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://cozastore_mongo_db:27017/
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    depends_on:
      - cozastore_mongo_db
    networks:
      - cozastore-network

  cozastore-cart-service:
    build:
      context: ./
      dockerfile: cart-service
    ports:
      - "8086:8086"
    container_name: cozastore-cart-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://cozastore_mongo_db:27017/
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    depends_on:
      - cozastore_mongo_db
    networks:
      - cozastore-network

  cozastore-media-service:
    build:
      context: ./
      dockerfile: media-service
    ports:
      - "8089:8089"
    container_name: cozastore-media-service
    environment:
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    networks:
      - cozastore-network

  cozastore-security-service:
    build:
      context: ./
      dockerfile: security-service
    ports:
      - "8085:8085"
    container_name: cozastore-security-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cozastore_mysql_db:3306/cozastoreVault
      RABBIT_MQ_HOST: rabbitmq
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    depends_on:
      - cozastore_mysql_db
    networks:
      - cozastore-network

  cozastore-user-service:
    build:
      context: ./
      dockerfile: user-service
    ports:
      - "8083:8083"
    container_name: cozastore-user-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://cozastore_mongo_db:27017/
      RABBIT_MQ_HOST: rabbitmq
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    depends_on:
      - cozastore_mongo_db
    networks:
      - cozastore-network

  cozastore-api-gateway:
    build:
      context: ./
      dockerfile: api-gateway
    ports:
      - "9000:9000"
    container_name: cozastore-api-gateway
    environment:
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    networks:
      - cozastore-network

  cozastore-discovery-server:
    build:
      context: ./
      dockerfile: discovery-server
    ports:
      - "8761:8761"
    container_name: cozastore-discovery-server
    environment:
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    networks:
      - cozastore-network

  cozastore-search-service:
    build:
      context: ./
      dockerfile: search-service
    ports:
      - "8087:8087"
    container_name: cozastore-search-service
    environment:
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    networks:
      - cozastore-network

  cozastore_mysql_db:
    image: mysql:latest
    container_name: cozastore_mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 618619
      MYSQL_DATABASE: cozastoreVault
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - cozastore-network

  cozastore_rabbitMQ:
    image: rabbitmq:3.12-management
    container_name: cozastore_rabbitMQ
    restart: always
    ports:
      - "5672:5672"
    networks:
      - cozastore-network

  cozastore_redis:
    image: redis:latest
    container_name: cozastore_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - cozastore-network

  cozastore_mongo_db:
    image: mongo:latest
    container_name: cozastore_mongo_db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - cozastore-network

  loki:
    image: grafana/loki:latest
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"                                   # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    networks:
      - cozastore-network

  tempo:
    image: grafana/tempo:main-0c1eb27
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml:ro
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "9411:9411" # zipkin
      - "4317:4317" # otlp grpc ingest
      - "4318:4318" # otlp http ingest
    networks:
      - cozastore-network

networks:
  cozastore-network:
    driver: bridge