version: '3'
services:
  cozastore-product-service:
    image: thelocal69/cozastore_product_service:latest
    ports:
      - "8080:8080"
    container_name: cozastore-product-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://cozastore_mongo_db:27017/
      REDIS_HOST: cozastore_redis
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    depends_on:
      - cozastore_mongo_db
    networks:
      - cozastore-network

  cozastore-order-service:
    image: thelocal69/cozastore_order_service:latest
    ports:
      - "8081:8081"
    container_name: cozastore-order-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cozastore_mysql_db:3307/cozastoreVault
      REDIS_HOST: cozastore_redis
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    depends_on:
      - cozastore_mysql_db
    networks:
      - cozastore-network

  cozastore-blog-service:
    image: thelocal69/cozastore_blog_service:latest
    ports:
      - "8084:8084"
    container_name: cozastore-blog-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://cozastore_mongo_db:27017/
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    depends_on:
      - cozastore_mongo_db
    networks:
      - cozastore-network

  cozastore-carousel-service:
    image: thelocal69/cozastore_carousel_service:latest
    ports:
      - "8082:8082"
    container_name: cozastore-carousel-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://cozastore_mongo_db:27017/
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    depends_on:
      - cozastore_mongo_db
    networks:
      - cozastore-network

  cozastore-cart-service:
    image: thelocal69/cozastore_cart_service:latest
    ports:
      - "8086:8086"
    container_name: cozastore-cart-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://cozastore_mongo_db:27017/
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    depends_on:
      - cozastore_mongo_db
    networks:
      - cozastore-network

  cozastore-media-service:
    image: thelocal69/cozastore_media_service:latest
    ports:
      - "8089:8089"
    container_name: cozastore-media-service
    environment:
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    networks:
      - cozastore-network

  cozastore-security-service:
    image: thelocal69/cozastore_security_service:latest
    ports:
      - "8085:8085"
    container_name: cozastore-security-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cozastore_mysql_db:3307/cozastoreVault
      RABBIT_MQ_HOST: rabbitmq
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    depends_on:
      - cozastore_mysql_db
    networks:
      - cozastore-network

  cozastore-user-service:
    image: thelocal69/cozastore_user_service:latest
    ports:
      - "8083:8083"
    container_name: cozastore-user-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://cozastore_mongo_db:27017/
      RABBIT_MQ_HOST: rabbitmq
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    depends_on:
      - cozastore_mongo_db
    networks:
      - cozastore-network

  cozastore-api-gateway:
    image: thelocal69/cozastore_api_gateway:latest
    ports:
      - "9000:9000"
    container_name: cozastore-api-gateway
    environment:
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    networks:
      - cozastore-network

  cozastore-discovery-server:
    image: thelocal69/cozastore_discovery_server:latest
    ports:
      - "8761:8761"
    container_name: cozastore-discovery-server
    environment:
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    networks:
      - cozastore-network

  cozastore-search-service:
    image: thelocal69/cozastore_search_service:latest
    ports:
      - "8087:8087"
    container_name: cozastore-search-service
    environment:
      EUREKA_HOST: cozastore-discovery-server
      GATE_WAY_HOST: cozastore-api-gateway
    networks:
      - cozastore-network

  cozastore_mysql_db:
    image: mysql:latest
    container_name: cozastore_mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 618619
      MYSQL_DATABASE: cozastoreVault
    ports:
      - "3307:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - cozastore-network

  cozastore_rabbitMQ:
    image: rabbitmq:3.12-management
    container_name: cozastore_rabbitMQ
    restart: always
    ports:
      - "5672:5672"
    networks:
      - cozastore-network

  cozastore_redis:
    image: redis:latest
    container_name: cozastore_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - cozastore-network

  cozastore_mongo_db:
    image: mongo:latest
    container_name: cozastore_mongo_db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - cozastore-network

  prometheus:
    image: prom/prometheus
    container_name: cozastore_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus-test/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana-enterprise
    container_name: cozastore_grafana
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    restart: unless-stopped
    ports:
      - '4040:3000'

  loki:
    image: grafana/loki:latest
    container_name: cozastore_loki_log
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    restart: always
    ports:
      - "3100:3100"                                   # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    networks:
      - cozastore-network

  tempo:
    image: grafana/tempo:main-0c1eb27
    container_name: cozastore_tempo
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml:ro
      - ./tempo-data:/tmp/tempo
    restart: always
    ports:
      - "14268"  # jaeger ingest
      - "9411:9411" # zipkin
      - "4317:4317" # otlp grpc ingest
      - "4318:4318" # otlp http ingest
    networks:
      - cozastore-network

#  elasticsearch:
#    image: elasticsearch:8.9.2
#    ports:
#      - "9200:9200"
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#      - ES_JAVA_OPTS=-MSG -Xmx8g
#
#  kibana:
#    image: kibana:8.9.2
#    ports:
#      - "5601:5601"
#    environment:
#      - ELASTICSEARCH_URL=http://elasticsearch:9200
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

networks:
  cozastore-network:
    driver: bridge