spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: discovery_server
          uri: http://localhost:${EUREKA.PORT:8761}/eureka
          predicates:
            - Path=/eureka/web

        - id: security_service
          uri: http://localhost:${SECURITY.PORT:8085}
          predicates:
            - Path=/api/account/**

        - id: product_service
          uri: http://localhost:${PRODUCT.PORT:8080}
          predicates:
            - Path=/api/product/**

        - id: category_service
          uri: http://localhost:${PRODUCT.PORT:8080}
          predicates:
            - Path=/api/category/**

        - id: color_service
          uri: http://localhost:${PRODUCT.PORT:8080}
          predicates:
            - Path=/api/color/**

        - id: size_service
          uri: http://localhost:${PRODUCT.PORT:8080}
          predicates:
            - Path=/api/size/**

        - id: blog_service
          uri: http://localhost:${BLOG.PORT:8084}
          predicates:
            - Path=/api/blog/**

        - id: carousel_service
          uri: http://localhost:${CAROUSEL.PORT:8082}
          predicates:
            - Path=/api/carousel/**

        - id: cart_service
          uri: http://localhost:${CART.PORT:8086}
          predicates:
            - Path=/api/cart/**

        - id: media_service
          uri: http://localhost:${MEDIA.PORT:8089}
          predicates:
            - Path=/api/media/**

        - id: search_service
          uri: http://localhost:${SEARCH.PORT:8087}
          predicates:
            - Path=/api/search/**

        - id: order_service
          uri: http://localhost:${ORDER.PORT:8081}
          predicates:
            - Path=/api/order/**

        - id: user_service
          uri: http://localhost:${USER.PORT:8083}
          predicates:
            - Path=/api/user/**

server:
  port: ${API_GATEWAY_PORT:9000}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA.PORT:8761}/eureka

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: info
