spring:
  application:
    name: media-service
server:
  port: ${MEDIA.PORT:8089}

path:
  root_path: ${user.home}/Desktop/cozastore_media/
  domain_url: http://localhost:${API_GATEWAY_PORT:9000}

gate-way:
  host: ${GATE_WAY_HOST:http://localhost}
  port: ${GATE_WAY_PORT:9000}

cloudinary:
  api-key: ${API_KEY:987765592191916}
  api-secret: ${API_SECRET:Gp6JgFX8YiNmS2bkJcBQP4C7jJw}
  cloud-name: ${CLOUD_NAME:detvyr8w4}

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: "1.0"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
    otlp:
      tracing:
        endpoint: http://localhost:4318/v1/traces
    tracing:
      sampling:
        probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA.PORT:8761}/eureka