spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${SPRING_DATA_USER_DB_URI:mongodb://localhost:27017/cozastore-user-service}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}

server:
  port: ${USER.PORT:8083}

gate-way:
  host: ${GATE_WAY_HOST:http://localhost}
  port: ${GATE_WAY_PORT:9000}

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: "1.0"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
    otlp:
      tracing:
        endpoint: http://localhost:4318/v1/traces
    tracing:
      sampling:
        probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA.PORT:8761}/eureka

rabbitmq:
  queue:
    name_changepwd: user.password.queue
    name_ban: user.ban.queue
  exchange:
    name: topic.exchange
  routing:
    key_pwd: /access/pwd
    key_ban: /access/ban
  account:
    queue:
      name_register: user.register.queue
    exchange:
      name: register.exchange
    routing:
      key_register: /account/register