spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST:localhost}:3306/cozastore_order_service}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:618619}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA.PORT:8761}/eureka