spring:
  application:
    name: cart-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/cozastore-cart-service}

server:
  port: ${CART.PORT:8086}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA.PORT:8761}/eureka